import React from 'react';
import { useStore } from './store';
import { Card, CardContent, CardHeader, CardTitle } from './components/ui/card';
import { Badge } from './components/ui/badge';
import { Download, Clock, Database, CheckCircle2, XCircle, ArrowRight, Zap, Target, Activity } from 'lucide-react';
import { Button } from './components/ui/button';

export const ExperimentSummary = () => {
  const { simulationResults, activeScenario, versions } = useStore();

  if (!simulationResults) {
    return (
      <div className="flex-1 p-8 flex items-center justify-center">
        <div className="text-center space-y-4">
          <Activity className="h-12 w-12 text-muted-foreground mx-auto" />
          <h2 className="text-2xl font-bold">No Summary Available</h2>
          <p className="text-muted-foreground">Run a simulation to generate an experiment summary.</p>
        </div>
      </div>
    );
  }

  const { kpis, readiness, executive_summary, rule_insights, workflow_observations } = simulationResults;

  const handlePrint = () => {
    window.print();
  };

  const currentVersion = versions.length > 0 ? `v${versions[versions.length - 1].version_number} (Latest)` : 'Unsaved Draft';
  const duration = kpis.averageDecisionTimeMs ? `${(kpis.averageDecisionTimeMs * kpis.totalTransactions / 1000).toFixed(2)}s` : '0.00s';
  const experimentId = `EXP-${Math.random().toString(36).substr(2, 6).toUpperCase()}`;

  return (
    <div className="relative">
      {/* Action Bar (Hidden when printing) */}
      <div className="flex justify-end mb-4 print:hidden">
        <Button onClick={handlePrint} variant="outline" className="bg-background">
          <Download className="w-4 h-4 mr-2" />
          Export PDF Report
        </Button>
      </div>

      {/* The Printable Report */}
      <div id="experiment-summary-report" className="space-y-8 bg-background text-foreground print:bg-white print:text-black">
        
        {/* Header */}
        <div className="border-b pb-6 print:border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-4xl font-bold tracking-tight mb-2 print:text-black">Experiment Summary</h1>
              <p className="text-muted-foreground print:text-gray-600">Autogenerated Simulation Insights</p>
            </div>
            <div className="text-right text-sm space-y-1 text-muted-foreground print:text-gray-600">
              <p><span className="font-semibold text-foreground print:text-black">ID:</span> {experimentId}</p>
              <p><span className="font-semibold text-foreground print:text-black">Date:</span> {new Date().toLocaleString()}</p>
              <p><span className="font-semibold text-foreground print:text-black">Version:</span> {currentVersion}</p>
            </div>
          </div>
        </div>

        {/* Overview Details */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <Card className="print:border-gray-200 print:shadow-none">
            <CardContent className="p-4 flex flex-col justify-center">
              <span className="text-xs text-muted-foreground uppercase tracking-wider font-semibold mb-1 print:text-gray-500">Scenario</span>
              <span className="font-medium flex items-center"><Database className="w-4 h-4 mr-1 text-primary print:text-gray-700"/> {activeScenario.replace('_', ' ').toUpperCase()}</span>
            </CardContent>
          </Card>
          <Card className="print:border-gray-200 print:shadow-none">
            <CardContent className="p-4 flex flex-col justify-center">
              <span className="text-xs text-muted-foreground uppercase tracking-wider font-semibold mb-1 print:text-gray-500">Transactions</span>
              <span className="font-medium flex items-center"><Target className="w-4 h-4 mr-1 text-primary print:text-gray-700"/> {kpis.totalTransactions.toLocaleString()}</span>
            </CardContent>
          </Card>
          <Card className="print:border-gray-200 print:shadow-none">
            <CardContent className="p-4 flex flex-col justify-center">
              <span className="text-xs text-muted-foreground uppercase tracking-wider font-semibold mb-1 print:text-gray-500">Duration</span>
              <span className="font-medium flex items-center"><Clock className="w-4 h-4 mr-1 text-primary print:text-gray-700"/> {duration}</span>
            </CardContent>
          </Card>
          <Card className="print:border-gray-200 print:shadow-none">
            <CardContent className="p-4 flex flex-col justify-center">
              <span className="text-xs text-muted-foreground uppercase tracking-wider font-semibold mb-1 print:text-gray-500">Avg Latency</span>
              <span className="font-medium flex items-center"><Zap className="w-4 h-4 mr-1 text-primary print:text-gray-700"/> {kpis.averageDecisionTimeMs.toFixed(2)} ms</span>
            </CardContent>
          </Card>
        </div>

        {/* Executive Summary */}
        <section>
          <h2 className="text-xl font-semibold mb-3 border-b pb-1 print:border-gray-200 print:text-black">Executive Summary</h2>
          <p className="text-lg leading-relaxed text-muted-foreground print:text-gray-700">{executive_summary}</p>
        </section>

        {/* Deployment Readiness */}
        <section>
          <h2 className="text-xl font-semibold mb-3 border-b pb-1 print:border-gray-200 print:text-black">Deployment Summary</h2>
          <Card className={`border-2 print:shadow-none print:border-gray-200 ${readiness.score > 80 ? 'border-emerald-500' : readiness.score > 50 ? 'border-amber-500' : 'border-destructive'}`}>
            <CardHeader className="pb-2">
              <CardTitle className="text-lg flex items-center justify-between print:text-black">
                Deployment Readiness Score
                <span className={`text-2xl font-bold ${readiness.score > 80 ? 'text-emerald-500 print:text-black' : readiness.score > 50 ? 'text-amber-500 print:text-black' : 'text-destructive print:text-black'}`}>
                  {readiness.score}/100
                </span>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid md:grid-cols-3 gap-6 pt-2">
                <div>
                  <h4 className="text-sm font-semibold text-emerald-500 flex items-center mb-2 print:text-gray-800"><CheckCircle2 className="w-4 h-4 mr-1" /> Strengths</h4>
                  <ul className="text-sm space-y-1 text-muted-foreground print:text-gray-700">
                    {readiness.strengths.map((s, i) => <li key={i}>• {s}</li>)}
                    {readiness.strengths.length === 0 && <li>None detected</li>}
                  </ul>
                </div>
                <div>
                  <h4 className="text-sm font-semibold text-destructive flex items-center mb-2 print:text-gray-800"><XCircle className="w-4 h-4 mr-1" /> Weaknesses & Risks</h4>
                  <ul className="text-sm space-y-1 text-muted-foreground print:text-gray-700">
                    {readiness.weaknesses.map((s, i) => <li key={i}>• {s}</li>)}
                    {readiness.weaknesses.length === 0 && <li>None detected</li>}
                  </ul>
                </div>
                <div>
                  <h4 className="text-sm font-semibold text-primary flex items-center mb-2 print:text-gray-800"><ArrowRight className="w-4 h-4 mr-1" /> Next Steps</h4>
                  <ul className="text-sm space-y-1 text-muted-foreground print:text-gray-700">
                    {readiness.recommendations.map((s, i) => <li key={i}>• {s}</li>)}
                    {readiness.recommendations.length === 0 && <li>Workflow looks great!</li>}
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </section>

        {/* Workflow Observations */}
        <section>
          <h2 className="text-xl font-semibold mb-3 border-b pb-1 print:border-gray-200 print:text-black">Workflow Observations</h2>
          <ul className="space-y-3">
            {workflow_observations.map((obs, idx) => (
              <li key={idx} className="flex items-start bg-muted/30 p-3 rounded-lg print:bg-transparent print:p-0 print:mb-2">
                <ArrowRight className="w-5 h-5 mr-3 text-muted-foreground shrink-0 mt-0.5 print:hidden" />
                <span className="text-base text-foreground print:text-gray-800">
                  <span className="hidden print:inline mr-2">•</span>
                  {obs}
                </span>
              </li>
            ))}
          </ul>
        </section>

        {/* Rule Insights */}
        <section className="print-break-inside-avoid">
          <h2 className="text-xl font-semibold mb-3 border-b pb-1 print:border-gray-200 print:text-black">Rule Insights</h2>
          <div className="grid md:grid-cols-2 gap-4">
            {rule_insights.map((rule) => (
              <Card key={rule.node_id} className="print:shadow-none print:border-gray-300">
                <CardContent className="p-5">
                  <div className="flex items-center justify-between mb-3">
                    <h3 className="font-semibold text-lg flex items-center print:text-black">
                      {rule.status} {rule.rule_name}
                    </h3>
                  </div>
                  <ul className="space-y-2 text-sm text-muted-foreground print:text-gray-700">
                    {rule.observations.map((obs, idx) => (
                      <li key={idx} className="flex items-start">
                        <span className="mr-2 opacity-50">•</span> {obs}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
            {rule_insights.length === 0 && (
              <p className="text-muted-foreground col-span-2">No rule insights generated. Ensure you have condition nodes in your workflow.</p>
            )}
          </div>
        </section>
        
        {/* Print Footer */}
        <div className="hidden print:block fixed bottom-0 left-0 right-0 text-center text-xs text-gray-400 pb-4 border-t border-gray-200 pt-2">
          Generated by Aegis Enterprise Platform
        </div>
      </div>
    </div>
  );
};
